version: 1.34.{build}
image: Visual Studio 2019


environment:
  matrix:
  - PlatformToolset: v142_xp

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set platform_input=x64
    - if "%platform%"=="Win32" set platform_input=Win32
    
build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - cd NppJSONViewer
    - msbuild NppJSONViewer.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
    - path: NppJSONViewer\x64\Release\NPPJSONViewer.dll
      name: x64
    - path: NppJSONViewer\Win32\Release\NPPJSONViewer.dll
      name: Win32
