version: 2.0.1.{build}
image: Visual Studio 2022


environment:
  matrix:
  - PlatformToolset: v143

platform:
    - x64
    - Win32
    - ARM64

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set platform_input=x64
    - if "%platform%"=="Win32" set platform_input=Win32
    - if "%platform%"=="ARM64" set platform_input=ARM64
    
build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - cd NppJSONViewer
    - git submodule update --init --recursive
    - msbuild NppJSONViewer.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
    - path: NppJSONViewer\Build\Bin\Release\x64\NPPJSONViewer.dll
      name: x64
      type: binary
    - path: NppJSONViewer\Build\Bin\Release\x64\NPPJSONViewer.pdb
      name: x64
      type: symbols

    - path: NppJSONViewer\Build\Bin\Release\Win32\NPPJSONViewer.dll
      name: Win32
      type: binary
    - path: NppJSONViewer\Build\Bin\Release\Win32\NPPJSONViewer.pdb
      name: Win32
      type: symbols

    - path: NppJSONViewer\Build\Bin\Release\ARM64\NPPJSONViewer.dll
      name: ARM64
      type: binary
    - path: NppJSONViewer\Build\Bin\Release\ARM64\NPPJSONViewer.pdb
      name: ARM64
      type: symbols
